Test notebooks

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -12,6 +12,13 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+availableSecrets:
+  secretManager:
+  - versionName: projects/gke-ai-eco-dev/secrets/cloudbuild-kaggle-username/versions/latest
+    env: 'KAGGLE_USERNAME'
+  - versionName: projects/gke-ai-eco-dev/secrets/cloudbuild-kaggle-key/versions/latest
+    env: 'KAGGLE_KEY'
+
 steps:
   - id: 'validate platform'
     name: 'gcr.io/$PROJECT_ID/terraform'
@@ -70,123 +77,124 @@ steps:
     allowFailure: true
     waitFor: ['validate platform', 'validate ray', 'validate jupyterhub', validate rag]
 
-  - id: 'test ray cluster'
-    name: 'gcr.io/$PROJECT_ID/terraform'
-    entrypoint: 'sh'
-    args:
-      - '-c'
-      - |
-        set -e
+  # - id: 'test ray cluster'
+  #   name: 'gcr.io/$PROJECT_ID/terraform'
+  #   entrypoint: 'sh'
+  #   args:
+  #     - '-c'
+  #     - |
+  #       set -e
 
-        # Get kube config
-        gcloud container clusters get-credentials \
-        ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        --location $_REGION \
-        --project $PROJECT_ID 
+  #       # Get kube config
+  #       gcloud container clusters get-credentials \
+  #       ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+  #       --location $_REGION \
+  #       --project $PROJECT_ID 
 
-        cd /workspace/applications/ray/
-        terraform apply \
-        -var-file=workloads.tfvars \
-        -var=project_id=$PROJECT_ID \
-        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        -var=cluster_location=$_REGION \
-        -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID \
-        -var=workload_identity_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=gcs_bucket=gke-aieco-ray-$SHORT_SHA-$_BUILD_ID \
-        -auto-approve -no-color -lock=false
-        echo "pass" > /workspace/user_result.txt
+  #       cd /workspace/applications/ray/
+  #       terraform apply \
+  #       -var-file=workloads.tfvars \
+  #       -var=project_id=$PROJECT_ID \
+  #       -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+  #       -var=cluster_location=$_REGION \
+  #       -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID \
+  #       -var=workload_identity_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
+  #       -var=gcs_bucket=gke-aieco-ray-$SHORT_SHA-$_BUILD_ID \
+  #       -auto-approve -no-color -lock=false
+  #       echo "pass" > /workspace/user_result.txt
 
-        # Make sure pods are running
-        kubectl wait --all pods -n ml-$SHORT_SHA-$_BUILD_ID --for=condition=Ready --timeout=300s
-        kubectl port-forward -n ml-$SHORT_SHA-$_BUILD_ID service/ray-cluster-kuberay-head-svc 8265:8265 &
-        # Wait port-forwarding to take its place
-        sleep 5s
+  #       # Make sure pods are running
+  #       kubectl wait --all pods -n ml-$SHORT_SHA-$_BUILD_ID --for=condition=Ready --timeout=300s
+  #       kubectl port-forward -n ml-$SHORT_SHA-$_BUILD_ID service/ray-cluster-kuberay-head-svc 8265:8265 &
+  #       # Wait port-forwarding to take its place
+  #       sleep 5s
 
-        ray job submit \
-        --address=http://127.0.0.1:8265 -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
-        echo "pass" > /workspace/ray_result.txt
-    allowFailure: true
-    waitFor: ['create gke cluster']
+  #       ray job submit \
+  #       --address=http://127.0.0.1:8265 -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
+  #       echo "pass" > /workspace/ray_result.txt
+  #   allowFailure: true
+  #   waitFor: ['create gke cluster']
 
-  - id: 'cleanup ray cluster'
-    name: 'gcr.io/$PROJECT_ID/terraform'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        set -e
+  # - id: 'cleanup ray cluster'
+  #   name: 'gcr.io/$PROJECT_ID/terraform'
+  #   entrypoint: 'bash'
+  #   args:
+  #     - '-c'
+  #     - |
+  #       set -e
 
-        cd /workspace/applications/ray/
-        terraform destroy \
-        -var-file=workloads.tfvars \
-        -var=project_id=$PROJECT_ID \
-        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        -var=cluster_location=$_REGION \
-        -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID \
-        -var=workload_identity_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=gcs_bucket=gke-aieco-ray-$SHORT_SHA-$_BUILD_ID \
-        -auto-approve -no-color -lock=false
+  #       cd /workspace/applications/ray/
+  #       terraform destroy \
+  #       -var-file=workloads.tfvars \
+  #       -var=project_id=$PROJECT_ID \
+  #       -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+  #       -var=cluster_location=$_REGION \
+  #       -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID \
+  #       -var=workload_identity_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
+  #       -var=gcs_bucket=gke-aieco-ray-$SHORT_SHA-$_BUILD_ID \
+  #       -auto-approve -no-color -lock=false
 
-    allowFailure: true
-    waitFor: ['test ray cluster']
+  #   allowFailure: true
+  #   waitFor: ['test ray cluster']
 
-  - id: 'test jupyterhub'
-    name: 'gcr.io/$PROJECT_ID/terraform'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        set -e
+  # - id: 'test jupyterhub'
+  #   name: 'gcr.io/$PROJECT_ID/terraform'
+  #   entrypoint: 'bash'
+  #   args:
+  #     - '-c'
+  #     - |
+  #       set -e
 
-        cd /workspace/modules/jupyter/tests
-        python3 change_jupyter_config.py $_AUTOPILOT_CLUSTER
+  #       cd /workspace/modules/jupyter/tests
+  #       python3 change_jupyter_config.py $_AUTOPILOT_CLUSTER
 
-        cd /workspace/applications/jupyter
-        terraform apply \
-        -var-file=workloads-without-iap.example.tfvars \
-        -var=project_id=$PROJECT_ID \
-        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID \
-        -var=workload_identity_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=gcs_bucket=gke-aieco-jupyter-$SHORT_SHA-$_BUILD_ID \
-        -auto-approve -no-color -lock=false
-        echo "pass" > /workspace/jupyterhub_tf_result.txt
+  #       cd /workspace/applications/jupyter
+  #       terraform apply \
+  #       -var-file=workloads-without-iap.example.tfvars \
+  #       -var=project_id=$PROJECT_ID \
+  #       -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+  #       -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID \
+  #       -var=workload_identity_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
+  #       -var=gcs_bucket=gke-aieco-jupyter-$SHORT_SHA-$_BUILD_ID \
+  #       -auto-approve -no-color -lock=false
+  #       echo "pass" > /workspace/jupyterhub_tf_result.txt
 
-        kubectl wait --all pods -n ml-$SHORT_SHA-$_BUILD_ID --for=condition=Ready --timeout=300s
-        kubectl get services -n ml-$SHORT_SHA-$_BUILD_ID
-        kubectl port-forward -n ml-$SHORT_SHA-$_BUILD_ID service/proxy-public 9443:80 &
-        # Wait port-forwarding to take its place
-        sleep 5s
+  #       kubectl wait --all pods -n ml-$SHORT_SHA-$_BUILD_ID --for=condition=Ready --timeout=300s
+  #       kubectl get services -n ml-$SHORT_SHA-$_BUILD_ID
+  #       kubectl port-forward -n ml-$SHORT_SHA-$_BUILD_ID service/proxy-public 9443:80 &
+  #       # Wait port-forwarding to take its place
+  #       sleep 5s
 
-        cd /workspace/modules/jupyter/tests
-        python3 test_hub.py "127.0.0.1:9443" $_AUTOPILOT_CLUSTER
-        echo "pass" > /workspace/jupyterhub_test_result.txt
-    allowFailure: true
+  #       cd /workspace/modules/jupyter/tests
+  #       python3 test_hub.py "127.0.0.1:9443" $_AUTOPILOT_CLUSTER
+  #       echo "pass" > /workspace/jupyterhub_test_result.txt
+  #   allowFailure: true
 
-  - id: 'cleanup jupyterhub'
-    name: 'gcr.io/$PROJECT_ID/terraform'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        set -e
+  # - id: 'cleanup jupyterhub'
+  #   name: 'gcr.io/$PROJECT_ID/terraform'
+  #   entrypoint: 'bash'
+  #   args:
+  #     - '-c'
+  #     - |
+  #       set -e
 
-        cd /workspace/applications/jupyter/
-        terraform destroy \
-        -var-file=workloads-without-iap.example.tfvars \
-        -var=project_id=$PROJECT_ID \
-        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID \
-        -var=workload_identity_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=gcs_bucket=gke-aieco-jupyter-$SHORT_SHA-$_BUILD_ID \
-        -auto-approve -no-color -lock=false
+  #       cd /workspace/applications/jupyter/
+  #       terraform destroy \
+  #       -var-file=workloads-without-iap.example.tfvars \
+  #       -var=project_id=$PROJECT_ID \
+  #       -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+  #       -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID \
+  #       -var=workload_identity_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
+  #       -var=gcs_bucket=gke-aieco-jupyter-$SHORT_SHA-$_BUILD_ID \
+  #       -auto-approve -no-color -lock=false
 
-    allowFailure: true
-    waitFor: ['test jupyterhub']
+  #   allowFailure: true
+  #   waitFor: ['test jupyterhub']
 
   - id: 'test rag'
     name: 'gcr.io/$PROJECT_ID/terraform'
     entrypoint: 'sh'
+    secretEnv: ['KAGGLE_USERNAME', 'KAGGLE_KEY']
     args:
       - '-c'
       - |
@@ -249,8 +257,19 @@ steps:
         cd /workspace/applications/rag/tests
         python3 test_frontend.py "127.0.0.1:8081"
         echo "pass" > /workspace/rag_frontend_result.txt
+
+        cd /workspace/
+        sed -i 's/<username>/$$KAGGLE_USERNAME/g' $(find . -type f -name "rag-kaggle-ray-sql-latest.ipynb")
+        sed -i 's/<token>/$$KAGGLE_KEY/g' $(find . -type f -name "rag-kaggle-ray-sql-latest.ipynb")
+        gsutil cp $(find . -type f -name "rag-kaggle-ray-sql-latest.ipynb") gs://gke-aieco-rag-$SHORT_SHA-$_BUILD_ID/notebooks/
+        kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID $(kubectl get pod -l app=jupyterhub,component=hub -n rag-$SHORT_SHA-$_BUILD_ID -o jsonpath="{.items[0].metadata.name}") -- jupyterhub token admin --log-level=CRITICAL | xargs python3 ./applications/rag/notebook_starter.py
+        kubectl wait --for=condition=Ready pod/jupyter-admin -n rag-$SHORT_SHA-$_BUILD_ID
+        kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID -c notebook -- jupyter nbconvert --to script /persist-data/rag-kaggle-ray-sql-latest.ipynb
+        kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID -c notebook -- ray job submit --working-dir . --address=http://127.0.0.1:8265 -- python rag-kaggle-ray-sql-latest.py
+
     allowFailure: true
-    waitFor: ['cleanup jupyterhub', 'cleanup ray cluster']
+    waitFor: ['create gke cluster']
+    # waitFor: ['cleanup jupyterhub', 'cleanup ray cluster']
 
   - id: 'cleanup rag'
     name: 'gcr.io/$PROJECT_ID/terraform'
